name: 'git-restore-mtime'
description: "Restore file's modified time (timestamp) based on git commits"
inputs:
  working-directory:
    description: "Where to run the action"
    required: false
    default: '.'
branding:
  icon: 'clock'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - name: Validate subscription
      shell: bash
      run: |
        API_URL="https://agent.api.stepsecurity.io/v1/github/$GITHUB_REPOSITORY/actions/subscription"

        # Set a timeout for the curl command (3 seconds)
        RESPONSE=$(curl --max-time 3 -s -w "%{http_code}" "$API_URL" -o /dev/null) || true
        CURL_EXIT_CODE=${?}

        # Check if the response code is not 200
        if [ $CURL_EXIT_CODE -ne 0 ]; then
          echo "Timeout or API not reachable. Continuing to next step."
        elif [ "$RESPONSE" = "200" ]; then
          :
        elif [ "$RESPONSE" = "403" ]; then
          echo "Subscription is not valid. Reach out to support@stepsecurity.io"
          exit 1
        else
          echo "Timeout or API not reachable. Continuing to next step."
        fi

    - name: Run git-restore-mtime
      shell: bash
      run: |
        cd "${{ inputs.working-directory }}" && "$GITHUB_ACTION_PATH"/git-restore-mtime
